### ISSUE TITLE
ValueError: 'llava' is already used by a Transformers config, pick another name.

### ISSUE THREAD

**Issue by Yaffa16** [AmirAbaskohi/Beyond-Words-A-Multimodal-Exploration-of-Persuasion-in-Memes#1]

**Comment by AmirAbaskohi** [comment]
Hi Yaffa16,

The issue arises from the introduction of 'llava' in the recent transformer versions, leading to a name conflict. Following the README's advice to create a new environment should resolve this problem. If it persists, consider installing transformers version 4.31.0.
